FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir google-cloud-firestore google-cloud-storage

COPY post_meeting.py .
COPY firebase_credentials.json .

EXPOSE 3001

CMD ["python", "post_meeting.py"] 