FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY restaurant_service.py .

EXPOSE 5002

# Use a simpler approach to run the Flask app
CMD ["python", "restaurant_service.py"] 