FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y ffmpeg

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY transcribe_service.py .
COPY key.json .

RUN mkdir -p uploads transcriptions

EXPOSE 5006

CMD ["python", "transcribe_service.py"] 