FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY account_service.py .

EXPOSE 5000

# Use a simpler approach to run the Flask app
CMD ["python", "account_service.py"] 