FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY config.py .
COPY composite_search_service.py .

EXPOSE 5015

CMD ["python", "composite_search_service.py"] 